- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 114
  package: cmake
  result: SUCCESS
  sources:
    !!python/unicode 'hash': [!!python/unicode '8822efa61f2a385e0bc83ca5819d608111b2168a',
      !!python/unicode '0a569d18496d4d384971d0c42be4300949896dc2']
    !!python/unicode 'repo': [!!python/unicode 'https://github.com/star-externals/zlib',
      !!python/unicode 'https://github.com/Kitware/CMake']
    !!python/unicode 'tag': [!!python/unicode 'v1.2.8', !!python/unicode 'v3.2.3']
  timestamp: 2015-07-10T13:33:50+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 113
  package: aliroot-test
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T13:12:49+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 112
  package: cmake
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T13:05:50+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 111
  package: aliroot-test
  result: FAILURE
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T12:14:20+0200
- alibuild: kf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 110
  package: zlib
  result: FAILURE
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T11:54:52+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 109
  package: aliroot-test
  result: FAILURE
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T11:45:51+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 108
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T11:41:41+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 107
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T10:27:29+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 106
  package: zlib
  result: SUCCESS
  sources:
    !!python/unicode 'hash': [!!python/unicode '8822efa61f2a385e0bc83ca5819d608111b2168a']
    !!python/unicode 'repo': [!!python/unicode 'https://github.com/star-externals/zlib@v1.2.8']
    tag: [!!python/unicode '8822efa61f2a385e0bc83ca5819d608111b2168a']
  timestamp: 2015-07-09T17:18:40+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 105
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T17:06:54+0200

