- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 120
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T15:47:58+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 118
  package: aliroot-test
  result: SUCCESS
  sources:
    !!python/unicode 'hash': [!!python/unicode 'v1.2.8', !!python/unicode 'v3.2.3',
      !!python/unicode 'v5-34-30', !!python/unicode 'v2-0', !!python/unicode 'a4284f60b494e7258b51692fa685f26cc54792e9']
    !!python/unicode 'repo': [!!python/unicode 'https://github.com/star-externals/zlib',
      !!python/unicode 'https://github.com/Kitware/CMake', !!python/unicode 'http://github.com/root-mirror/root',
      !!python/unicode 'http://root.cern.ch/git/geant3.git', !!python/unicode 'http://git.cern.ch/pub/AliRoot']
    !!python/unicode 'tag': [!!python/unicode 'v1.2.8', !!python/unicode 'v3.2.3',
      !!python/unicode 'v5-34-30', !!python/unicode 'v2-0', !!python/unicode 'master']
  timestamp: 2015-07-10T15:29:46+0200
- alibuild: alisw
  alidist: alisw
  architecture: slc7_x86-64
  jenkins_build_nr: 117
  package: aliroot-test
  result: FAILURE
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T15:23:31+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 116
  package: geant3
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T14:46:18+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 115
  package: zlib
  result: SUCCESS
  sources:
    !!python/unicode 'hash': [!!python/unicode 'v1.2.8']
    !!python/unicode 'repo': [!!python/unicode 'https://github.com/star-externals/zlib']
    !!python/unicode 'tag': [!!python/unicode 'v1.2.8']
  timestamp: 2015-07-10T14:36:22+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 114
  package: cmake
  result: SUCCESS
  sources:
    !!python/unicode 'hash': [!!python/unicode '8822efa61f2a385e0bc83ca5819d608111b2168a',
      !!python/unicode '0a569d18496d4d384971d0c42be4300949896dc2']
    !!python/unicode 'repo': [!!python/unicode 'https://github.com/star-externals/zlib',
      !!python/unicode 'https://github.com/Kitware/CMake']
    !!python/unicode 'tag': [!!python/unicode 'v1.2.8', !!python/unicode 'v3.2.3']
  timestamp: 2015-07-10T13:33:50+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 113
  package: aliroot-test
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T13:12:49+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 112
  package: cmake
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T13:05:50+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 111
  package: aliroot-test
  result: FAILURE
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T12:14:20+0200
- alibuild: kf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 110
  package: zlib
  result: FAILURE
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T11:54:52+0200

