- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 91
  package: aliroot-test
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 92
  package: aliroot-test
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 93
  package: aliroot-test
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 94
  package: aliroot-test
