- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 94
