- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 107
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-10T10:27:29+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 106
  package: zlib
  result: SUCCESS
  sources:
    !!python/unicode 'hash': [!!python/unicode '8822efa61f2a385e0bc83ca5819d608111b2168a']
    !!python/unicode 'repo': [!!python/unicode 'https://github.com/star-externals/zlib@v1.2.8']
    tag: [!!python/unicode '8822efa61f2a385e0bc83ca5819d608111b2168a']
  timestamp: 2015-07-09T17:18:40+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 105
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T17:06:54+0200
- alibuild: alisw
  alidist: alisw
  architecture: slc7_x86-64
  jenkins_build_nr: 104
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T17:05:43+0200
- alibuild: alisw
  alidist: alisw
  architecture: slc7_x86-64
  jenkins_build_nr: 103
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T16:43:46+0200
- alibuild: alisw
  alidist: alisw
  architecture: slc7_x86-64
  jenkins_build_nr: 102
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T16:42:49+0200
- alibuild: alisw
  alidist: alisw
  architecture: slc7_x86-64
  jenkins_build_nr: 101
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T16:39:21+0200
- alibuild: alisw
  alidist: alisw
  architecture: slc7_x86-64
  jenkins_build_nr: 100
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T15:53:00+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 99
  package: zlib
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-09T14:20:22+0200
- alibuild: ktf
  alidist: ktf
  architecture: slc7_x86-64
  jenkins_build_nr: 98
  package: aliroot-test
  result: SUCCESS
  sources:
    hash: []
    repo: []
    tag: []
  timestamp: 2015-07-08T18:18:10+0200

