- {alibuild: alisw, alidist: alisw, architecture: slc7_x86-64, jenkins_build_nr: 103,
  package: zlib, result: SUCCESS, timestamp: '2015-07-09T16:43:46+0200'}
- {alibuild: alisw, alidist: alisw, architecture: slc7_x86-64, jenkins_build_nr: 102,
  package: zlib, result: SUCCESS, timestamp: '2015-07-09T16:42:49+0200'}
- {alibuild: alisw, alidist: alisw, architecture: slc7_x86-64, jenkins_build_nr: 101,
  package: zlib, result: SUCCESS, timestamp: '2015-07-09T16:39:21+0200'}
- {alibuild: alisw, alidist: alisw, architecture: slc7_x86-64, jenkins_build_nr: 100,
  package: zlib, result: SUCCESS, timestamp: '2015-07-09T15:53:00+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 99, package: zlib,
  result: SUCCESS, timestamp: '2015-07-09T14:20:22+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 98, package: aliroot-test,
  result: SUCCESS, timestamp: '2015-07-08T18:18:10+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 97, package: aliroot-test,
  result: SUCCESS, timestamp: '2015-07-08T16:31:42+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 96, package: zlib,
  result: SUCCESS, timestamp: '2015-07-08T15:08:06+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 95, package: zlib,
  result: ABORTED, timestamp: '2015-07-08T15:06:12+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 94, package: '',
  result: SUCCESS, timestamp: '2015-07-08T12:44:19+0200'}

