- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 91
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 92
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 93
- 
  architecture: slc7_x86-64
  alibuild: ktf
  alidist: ktf
  jenkins_build_nr: 94
