- {alibuild: alisw, alidist: alisw, architecture: slc7_x86-64, jenkins_build_nr: 100,
  result: SUCCESS, timestamp: '2015-07-09T15:53:00+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 99, result: SUCCESS,
  timestamp: '2015-07-09T14:20:22+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 98, result: SUCCESS,
  timestamp: '2015-07-08T18:18:10+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 97, result: SUCCESS,
  timestamp: '2015-07-08T16:31:42+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 96, result: SUCCESS,
  timestamp: '2015-07-08T15:08:06+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 95, result: ABORTED,
  timestamp: '2015-07-08T15:06:12+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 94, result: SUCCESS,
  timestamp: '2015-07-08T12:44:19+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 93, result: FAILURE,
  timestamp: '2015-07-08T10:59:49+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 92, result: FAILURE,
  timestamp: '2015-07-08T10:49:39+0200'}
- {alibuild: ktf, alidist: ktf, architecture: slc7_x86-64, jenkins_build_nr: 91, result: FAILURE,
  timestamp: '2015-07-07T17:09:38+0200'}

